### ISSUE TITLE
failed to resolve: use of undeclared type `Errno`

### ISSUE THREAD

**Issue by lengrongfu** [containers/youki#1812] opened 2023-04-13 14:53 UTC
Why this is error: https://github.com/containers/youki/actions/runs/4690386835/jobs/8313409869?pr=1811

```
error[E0433]: failed to resolve: use of undeclared type `Errno`
   --> crates/libcontainer/src/process/container_main_process.rs:123:23
    |
123 |             if err == Errno::ECHILD {
    |                       ^^^^^ use of undeclared type `Errno`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `libcontainer` due to previous error
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
````

I am very confused, this code already exists in the main branch, why does the ci fail.

**Comment by yihuaf** [comment] 2023-04-13 17:06
It is clippy fail, not compilation. I suspect that `clippy` is upgraded with some new rules. Today, we don't pin the clippy version.

**Comment by yihuaf** [comment] 2023-04-14 05:35
Interesting. I am not able to reproduce the exact compile error here, but the main branch fails with another compilation error in seccomp which we have not touched for a while...

**Comment by yihuaf** [comment] 2023-04-14 05:42
Can you try rebase to the tip of the tree? A few PR went in afterwards with clean CI runs.

**Comment by yihuaf** [comment] 2023-04-14 06:36
I can confirm that the latest tot doesn't have the issue. Please rebase and try again. Closing for now.

**Comment by yihuaf** [comment] 2023-04-21 22:09
Looks like we are seeing this error popping up in different places in CI now. Need further investigation.

**Closed** 2023-04-23 12:20 UTC
Labels: bug
