### ISSUE TITLE
youki delete bug

### ISSUE THREAD

**Issue by lengrongfu** [containers/youki#1640] opened 2023-03-08 12:26 UTC
I executed `youki run test` using a user with non-root privileges, and the execution failed, then executed `youki list` can find `test` this container, but executed `youki delete test` fail.

- youki list
```shell
ubuntu@myubuntu:~$ youki list
ID    PID  STATUS   BUNDLE                  CREATED  CREATOR
test       Stopped  /home/ubuntu/container
```

- youki delete
```shell
ubuntu@myubuntu:~$ youki delete test
[ERROR crates/youki/src/main.rs:138] 2023-03-08T19:11:04.971051412+08:00 error in executing command: failed to delete container test

Caused by:
    0: failed to load runtime spec for container test
    1: No such file or directory (os error 2)
Error: failed to delete container test

Caused by:
    0: failed to load runtime spec for container test
    1: No such file or directory (os error 2)
```

I found that there is only state.json file in the container data directory, not youki_ Config.json file, which is the root cause of deletion failure.

```shell
ubuntu@myubuntu:~$ tree /run/user/1000/youki
/run/user/1000/youki
└── test
    └── state.json

1 directory, 1 file
```

Currently I think there are two solutions:
1. After `youki run` fails, you should clear the operation.
2. In `youki delete`, it is compatible with the situation where `youki_config.json` does not exist.

need to discuss.

**Comment by yihuaf** [comment] 2023-03-08 16:20
I suspect that this is a duplicate of this fix: https://github.com/containers/youki/pull/1556

**Closed** 2023-03-10 05:32 UTC
Labels: bug
